name: gnn4co
channels:
  - pytorch
  - pyg
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - aiohttp=3.9.3=py310h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.3=py310haa95532_0
  - attrs=23.1.0=py310haa95532_0
  - blas=1.0=mkl
  - bottleneck=1.3.7=py310h9128911_0
  - brotli-python=1.0.9=py310hd77b12b_7
  - bzip2=1.0.8=h2bbff1b_5
  - ca-certificates=2024.3.11=haa95532_0
  - certifi=2024.2.2=py310haa95532_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.1=py310haa95532_0
  - cuda-cccl=12.4.127=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.4.127=0
  - cuda-runtime=11.8.0=0
  - debugpy=1.6.7=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - docplex=2.27.239=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=py310haa95532_0
  - exceptiongroup=1.2.0=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.13.1=py310haa95532_0
  - frozenlist=1.4.0=py310h2bbff1b_0
  - fsspec=2023.10.0=py310haa95532_0
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.37=py310haa95532_0
  - gmpy2=2.1.2=py310h7f96b67_0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.4=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.3=pyha63f2e9_0
  - ipython=8.20.0=py310haa95532_0
  - jedi=0.18.1=py310haa95532_1
  - jinja2=3.1.3=py310haa95532_0
  - joblib=1.4.0=py310haa95532_0
  - jupyter_client=8.6.0=py310haa95532_0
  - jupyter_core=5.5.0=py310haa95532_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libffi=3.4.4=hd77b12b_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libuv=1.44.2=h2bbff1b_0
  - lightning-utilities=0.9.0=py310haa95532_0
  - markupsafe=2.1.3=py310h2bbff1b_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.8=py310h2bbff1b_0
  - mkl_random=1.2.4=py310h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py310haa95532_0
  - multidict=6.0.4=py310h2bbff1b_0
  - nest-asyncio=1.6.0=py310haa95532_0
  - networkx=3.1=py310haa95532_0
  - numexpr=2.8.7=py310h2cd9be0_0
  - numpy=1.26.4=py310h055cbcc_0
  - numpy-base=1.26.4=py310h65a83cf_0
  - openpyxl=3.1.2=py310h2bbff1b_0
  - openssl=3.0.13=h2bbff1b_1
  - packaging=23.2=py310haa95532_0
  - pandas=2.2.1=py310h5da7b33_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - pip=23.3.1=py310haa95532_0
  - platformdirs=3.10.0=py310haa95532_0
  - plotly=5.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.43=py310haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=3.20.3=py310hd77b12b_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=5=hd3eb1b0_0
  - pyg=2.5.2=py310_torch_2.2.0_cu118
  - pygments=2.15.1=py310haa95532_1
  - pyparsing=3.0.9=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.14=he1021f5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.2.2=py3.10_cuda11.8_cudnn8_0
  - pytorch-cuda=11.8=h24eeafa_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py310haa95532_0
  - pywin32=305=py310h2bbff1b_0
  - pyyaml=6.0.1=py310h2bbff1b_0
  - pyzmq=25.1.2=py310hd77b12b_0
  - requests=2.31.0=py310haa95532_1
  - scikit-learn=1.3.0=py310h4ed8f06_1
  - scipy=1.13.0=py310h8640f81_0
  - sentry-sdk=1.9.0=py310haa95532_0
  - setproctitle=1.2.2=py310h2bbff1b_0
  - setuptools=68.2.2=py310haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.12=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tenacity=8.2.2=py310haa95532_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h2bbff1b_0
  - torchmetrics=1.3.2=pyhd8ed1ab_0
  - tornado=6.3.3=py310h2bbff1b_0
  - tqdm=4.65.0=py310h9909e9c_0
  - traitlets=5.7.1=py310haa95532_0
  - typing_extensions=4.9.0=py310haa95532_1
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.1.0=py310haa95532_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wandb=0.16.5=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xz=5.4.6=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - yarl=1.9.3=py310h2bbff1b_0
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - cplex==22.1.0.0
      - torch-scatter==2.1.2+pt22cu118
